training_params:
  max_epochs: 10
  auto_lr_find: true
  gpus: 0  #default value, can be changed with command line parameters: "--gpu 2"
model_params:
  model_type: vae
  lr: 0.01
  batch_size: 32
  latent_dim: 128 
  dataset: "mnist" #default value, can be changed with command line parameters
logger_params:
  name: "vae"
  save_dir: "logs/"